language: java
jdk:
- oraclejdk8
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
sudo: false # faster builds

script: "mvn cobertura:cobertura"

after_success:
- bash <(curl -s https://codecov.io/bash)