language: java
jdk:
- oraclejdk8
install:
- mvn -N io.takari:maven:wrapper
- mvn clean install
sudo: false # faster builds

script: 
- mvn cobertura:cobertura

after_success:
- bash <(curl -s https://codecov.io/bash)