language: java
jdk:
- oraclejdk8
install:
- mvn install -Dmaven.javadoc.skip=true -B -V
script:
- mvn test 
sudo: false # faster builds

script: 
- mvn cobertura:cobertura

after_success:
- bash <(curl -s https://codecov.io/bash) -t d25d7c42-7a9b-4dea-940c-0b754bcc7640